# The GKE kubelet needs authorization for scraping
deployKubelets: false
# GKE manages the kube-scheduler, -controller-manager and -etcd outside the cluster.
deployKubeScheduler: false
deployKubeControllerManager: false
deployKubeEtcd: false
# We expect users to install their own alertmanagers.
deployAlertManager: false
global:
  rbacEnable: false
prometheus:
  serviceMonitorNamespaceSelector:
    any: true
  ruleNamespaceSelector:
    any: true
  externalUrl: "https://${CLOUD_ROBOTICS_DOMAIN}/prometheus/"
  retention: "120d"
  storageSpec:
    volumeClaimTemplate:
      spec:
        storageClassName: ssd
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            # At the time of writing this, Prometheus ingests about 1500
            # samples/sec, which should result it ~17GB for the 120 days of
            # retention.
            # If higher ingestion throughput is observed, this should be
            # adjusted linearly.
            storage: 60Gi
grafana:
  serverDashboardConfigmaps:
  - extra-grafana-dashboards
  extraVars:
  - name: GF_SERVER_DOMAIN
    value: ${CLOUD_ROBOTICS_DOMAIN}
  - name: GF_SERVER_ROOT_URL
    value: "https://${CLOUD_ROBOTICS_DOMAIN}/grafana"
