apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: map-openapi
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-url: "http://token-vendor.default.svc.cluster.local/apis/core.token-vendor/v1/token.verify?robots=true"
spec:
  tls:
  - hosts:
    -  {{ .Values.domain }}
    secretName: tls
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /apis/core.map/
        backend:
          serviceName: map-endpoint
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: map-grpc
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/grpc-backend: "true"
    nginx.ingress.kubernetes.io/secure-backends: "false"
    nginx.ingress.kubernetes.io/auth-url: "http://token-vendor.default.svc.cluster.local/apis/core.token-vendor/v1/token.verify?robots=true"
spec:
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /cloudrobotics.map.v1alpha1.MapService/
        backend:
          serviceName: map-endpoint
          servicePort: 8081
