apiVersion: v1
kind: Service
metadata:
  name: map-endpoint
  annotations:
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http2
  selector:
    app: map-endpoint
  type: ClusterIP
