{{ if eq .Values.robot_authentication "true" }}
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: gcr-credential-refresher
spec:
  schedule: "*/10 * * * *" # every ten minutes
  jobTemplate:
    metadata:
      labels:
        app: gcr-credential-refresher
    spec:
      template:
        metadata:
          labels:
            app: gcr-credential-refresher
        spec:
          containers:
          - image: {{ .Values.images.gcr_credential_refresher }}
            name: gcr-credential-refresher
          restartPolicy: OnFailure
{{ end }}
