apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-relay-client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus-relay-client
    spec:
      containers:
      - args:
        - --backend_address
        - kube-prometheus.{{ .Release.Namespace }}.svc.cluster.local:9090
        - --backend_scheme
        - http
        - --relay_address
        - {{ .Values.domain }}
        - --relay_prefix
        - "/apis/core.prometheus-relay"
        - --server_name
        - "{{ .Values.robot.name }}"
        image: {{ .Values.images.http_relay_client }}
        name: prometheus-relay-client
        resources:
          requests:
            cpu: 20m
            memory: 100Mi
