apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-node-exporter
  labels:
    prometheus: kube-prometheus
spec:
  endpoints:
  - port: metrics
  selector:
    matchLabels:
      app: prometheus-node-exporter
