domain: "example.com"
project: "my-gcp-project"
deploy_environment: "GCP"

# Setting app_management to "false" will remove layer 2 (robot/cloud-master, etc).
app_management: "true"

# Setting robot_authentication to "false" will remove layer 1 resources that are not
# needed when simulating a robot with a GKE cluster, such as the
# metadata-server or gcr-credential-refresher.
robot_authentication: "true"

robot:
  name: ""
