apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana-operator
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana-operator
    spec:
      containers:
      - name: grafana-operator
        image: {{ .Values.images.grafana_operator }}
        args:
        - --target-namespace={{ .Release.Namespace }}
