apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prometheus-relay-server
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus-relay-server
    spec:
      containers:
      - name: server
        image: {{ .Values.images.http_relay_server }}
        args:
        - --port=80
        - --project_id={{ .Values.project }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 15
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-relay-server
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    # This is used by the ServiceMonitor.
    app: prometheus-relay-server
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: prometheus-relay-server
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus-relay-server
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/rewrite-target: /server
    nginx.ingress.kubernetes.io/auth-url: "http://token-vendor.default.svc.cluster.local/apis/core.token-vendor/v1/token.verify?robots=true"
spec:
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: tls
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /apis/core.prometheus-relay/server
        backend:
          serviceName: prometheus-relay-server
          servicePort: 80
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-relay-server
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    prometheus: kube-prometheus
spec:
  endpoints:
  - port: http
  selector:
    matchLabels:
      app: prometheus-relay-server
