apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-url: "http://oauth2-proxy.default.svc.cluster.local/apis/core.token-vendor/v1/token.verify"
    nginx.ingress.kubernetes.io/auth-signin: "https://{{ .Values.domain }}/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/secure-backends: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/configuration-snippet: |
      error_page 403 = /oauth2/start?rd=$escaped_request_uri;
spec:
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: tls
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /prometheus
        backend:
          serviceName: kube-prometheus
          servicePort: 9090
