apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubernetes-relay-client
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/auth-url: "http://token-vendor.default.svc.cluster.local/apis/core.token-vendor/v1/token.verify"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/rewrite-target: /client
spec:
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: tls
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /apis/core.kubernetes-relay/client
        backend:
          serviceName: kubernetes-relay-server
          servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubernetes-relay-server
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/rewrite-target: /server
    nginx.ingress.kubernetes.io/auth-url: "http://token-vendor.default.svc.cluster.local/apis/core.token-vendor/v1/token.verify?robots=true"
spec:
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: tls
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /apis/core.kubernetes-relay/server
        backend:
          serviceName: kubernetes-relay-server
          servicePort: 80
