apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubernetes-relay-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kubernetes-relay-server
    spec:
      containers:
      - name: server
        image: {{ .Values.images.http_relay_server }}
        args:
        - --port=80
        - --project_id={{ .Values.project }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 15
        ports:
        - name: http
          containerPort: 80
