apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cloud-robotics
  namespace: default
spec:
  secretName: tls
  issuerRef:
    name: letsencrypt-prod
  commonName: {{ .Values.domain }}
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - {{ .Values.domain }}
