{{ if eq .Values.app_management "true" }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cloud-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cloud-master
    spec:
      containers:
      - name: cloud-master
        args:
        - "--params=\
          domain={{ .Values.domain }},\
          project={{ .Values.project }},\
          deploy_environment={{ .Values.deploy_environment }},\
          oauth2_proxy.client_id={{ .Values.oauth2_proxy.client_id }}"
        image: {{ .Values.images.cloud_master }}
        env:
        - name: GOOGLE_CLOUD_PROJECT
          value: {{ .Values.project }}
{{ end }}
