apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubernetes-relay-client
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: kubernetes-relay-client
    spec:
      containers:
      - args:
        - --backend_address
        - "$(KUBERNETES_SERVICE_HOST):$(KUBERNETES_SERVICE_PORT)"
        - --backend_scheme
        - https
        - --authentication_token_file
        - "/var/run/secrets/kubernetes.io/serviceaccount/token"
        - --root_ca_file
        - "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
        - --relay_address
        - {{ .Values.domain }}
        - --relay_prefix
        - "/apis/core.kubernetes-relay"
        - --server_name
        - "{{ .Values.robot.name }}"
        image: {{ .Values.images.http_relay_client }}
        name: kubernetes-relay-client
        resources: {}
